package wizard

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// StackConfig holds all user-facing configuration for the RuleKit stack.
type StackConfig struct {
	// Database
	Store       string // "sqlite" | "postgres"
	DataDir     string // sqlite only
	DatabaseURL string // postgres only

	// Blob
	BlobStore         string // "fs" | "s3"
	S3Bucket          string
	S3Region          string
	S3Endpoint        string
	S3AccessKeyID     string
	S3SecretAccessKey string

	// Auth (always required by registry)
	JWTSecret     string
	AdminPassword string

	// SMTP
	SMTPEnabled  bool
	SMTPHost     string
	SMTPPort     int
	SMTPUsername string
	SMTPPassword string
	SMTPFrom     string
	SMTPUseTLS   bool

	// Network
	RegistryPort  int
	DashboardPort int
}

// Defaults returns a StackConfig populated with the spec's default values.
func Defaults() StackConfig {
	return StackConfig{
		Store:         "sqlite",
		DataDir:       "/data",
		BlobStore:     "fs",
		SMTPPort:      587,
		SMTPFrom:      "noreply@rulekit.dev",
		RegistryPort:  8080,
		DashboardPort: 3001,
	}
}

// ToEnv serializes the config to a .env file string.
func (c *StackConfig) ToEnv() string {
	var b strings.Builder

	b.WriteString("# Generated by rulekit onboard — do not edit manually.\n")
	b.WriteString("# Re-run 'rulekit onboard --reconfigure' to change settings.\n\n")

	b.WriteString(fmt.Sprintf("RULEKIT_ADDR=:%d\n", c.RegistryPort))

	// Database
	b.WriteString("\n# Database\n")
	b.WriteString(fmt.Sprintf("RULEKIT_STORE=%s\n", c.Store))
	if c.Store == "sqlite" {
		dir := c.DataDir
		if dir == "" {
			dir = "/data"
		}
		b.WriteString(fmt.Sprintf("RULEKIT_DATA_DIR=%s\n", dir))
	} else {
		b.WriteString(fmt.Sprintf("RULEKIT_DATABASE_URL=%s\n", c.DatabaseURL))
	}

	// Blob store
	b.WriteString("\n# Blob store\n")
	b.WriteString(fmt.Sprintf("RULEKIT_BLOB_STORE=%s\n", c.BlobStore))
	if c.BlobStore == "s3" {
		b.WriteString(fmt.Sprintf("RULEKIT_S3_BUCKET=%s\n", c.S3Bucket))
		b.WriteString(fmt.Sprintf("RULEKIT_S3_REGION=%s\n", c.S3Region))
		b.WriteString(fmt.Sprintf("RULEKIT_S3_ENDPOINT=%s\n", c.S3Endpoint))
		b.WriteString(fmt.Sprintf("RULEKIT_S3_ACCESS_KEY_ID=%s\n", c.S3AccessKeyID))
		b.WriteString(fmt.Sprintf("RULEKIT_S3_SECRET_ACCESS_KEY=%s\n", c.S3SecretAccessKey))
	}

	// Auth
	b.WriteString("\n# Auth\n")
	b.WriteString(fmt.Sprintf("RULEKIT_JWT_SECRET=%s\n", c.JWTSecret))
	b.WriteString(fmt.Sprintf("RULEKIT_ADMIN_PASSWORD=%s\n", c.AdminPassword))

	// SMTP
	if c.SMTPEnabled {
		b.WriteString("\n# SMTP\n")
		b.WriteString(fmt.Sprintf("RULEKIT_SMTP_HOST=%s\n", c.SMTPHost))
		b.WriteString(fmt.Sprintf("RULEKIT_SMTP_PORT=%d\n", c.SMTPPort))
		b.WriteString(fmt.Sprintf("RULEKIT_SMTP_USERNAME=%s\n", c.SMTPUsername))
		b.WriteString(fmt.Sprintf("RULEKIT_SMTP_PASSWORD=%s\n", c.SMTPPassword))
		b.WriteString(fmt.Sprintf("RULEKIT_SMTP_FROM=%s\n", c.SMTPFrom))
		b.WriteString(fmt.Sprintf("RULEKIT_SMTP_USE_TLS=%v\n", c.SMTPUseTLS))
	}

	// CORS
	b.WriteString("\n# CORS\n")
	b.WriteString(fmt.Sprintf("RULEKIT_CORS_ORIGINS=http://localhost:%d\n", c.DashboardPort))

	return b.String()
}

// WriteEnv atomically writes the .env content to path with 0600 permissions.
func WriteEnv(path, content string) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write env tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename env: %w", err)
	}
	return nil
}

// LoadFromEnv parses an existing .env file into a StackConfig.
// Unknown or missing keys are silently ignored (backward compatible).
func LoadFromEnv(path string) (*StackConfig, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open env file: %w", err)
	}
	defer f.Close()

	cfg := Defaults()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		k = strings.TrimSpace(k)
		v = strings.TrimSpace(v)
		applyEnvKey(&cfg, k, v)
	}
	return &cfg, scanner.Err()
}

func applyEnvKey(cfg *StackConfig, k, v string) {
	switch k {
	case "RULEKIT_STORE":
		cfg.Store = v
	case "RULEKIT_DATA_DIR":
		cfg.DataDir = v
	case "RULEKIT_DATABASE_URL":
		cfg.DatabaseURL = v
	case "RULEKIT_BLOB_STORE":
		cfg.BlobStore = v
	case "RULEKIT_S3_BUCKET":
		cfg.S3Bucket = v
	case "RULEKIT_S3_REGION":
		cfg.S3Region = v
	case "RULEKIT_S3_ENDPOINT":
		cfg.S3Endpoint = v
	case "RULEKIT_S3_ACCESS_KEY_ID":
		cfg.S3AccessKeyID = v
	case "RULEKIT_S3_SECRET_ACCESS_KEY":
		cfg.S3SecretAccessKey = v
	case "RULEKIT_JWT_SECRET":
		cfg.JWTSecret = v
	case "RULEKIT_ADMIN_PASSWORD":
		cfg.AdminPassword = v
	case "RULEKIT_SMTP_HOST":
		cfg.SMTPHost = v
		if v != "" {
			cfg.SMTPEnabled = true
		}
	case "RULEKIT_SMTP_PORT":
		if n, err := strconv.Atoi(v); err == nil {
			cfg.SMTPPort = n
		}
	case "RULEKIT_SMTP_USERNAME":
		cfg.SMTPUsername = v
	case "RULEKIT_SMTP_PASSWORD":
		cfg.SMTPPassword = v
	case "RULEKIT_SMTP_FROM":
		cfg.SMTPFrom = v
	case "RULEKIT_SMTP_USE_TLS":
		cfg.SMTPUseTLS = v == "true"
	case "RULEKIT_ADDR":
		port := strings.TrimPrefix(v, ":")
		if n, err := strconv.Atoi(port); err == nil {
			cfg.RegistryPort = n
		}
	case "RULEKIT_CORS_ORIGINS":
		parts := strings.Split(v, ":")
		if len(parts) == 3 {
			if n, err := strconv.Atoi(parts[2]); err == nil {
				cfg.DashboardPort = n
			}
		}
	}
}

// Summary returns a human-readable summary of the config, masking secrets.
func (c *StackConfig) Summary() string {
	var b strings.Builder

	// Database
	switch c.Store {
	case "postgres":
		masked := maskURL(c.DatabaseURL)
		fmt.Fprintf(&b, "  database    postgres · %s\n", masked)
	default:
		fmt.Fprintf(&b, "  database    sqlite\n")
	}

	// Blob
	switch c.BlobStore {
	case "s3":
		fmt.Fprintf(&b, "  blob        s3 · %s (%s)\n", c.S3Bucket, c.S3Region)
	default:
		fmt.Fprintf(&b, "  blob        filesystem\n")
	}

	// Auth
	fmt.Fprintf(&b, "  auth        jwt · admin / ***\n")

	// SMTP
	if c.SMTPEnabled {
		fmt.Fprintf(&b, "  smtp        %s:%d\n", c.SMTPHost, c.SMTPPort)
	}

	fmt.Fprintf(&b, "  registry    http://localhost:%d\n", c.RegistryPort)
	fmt.Fprintf(&b, "  dashboard   http://localhost:%d\n", c.DashboardPort)

	return b.String()
}

// maskURL replaces the password in a postgres:// URL with ***.
func maskURL(u string) string {
	if i := strings.Index(u, "://"); i >= 0 {
		rest := u[i+3:]
		if at := strings.Index(rest, "@"); at >= 0 {
			creds := rest[:at]
			if colon := strings.Index(creds, ":"); colon >= 0 {
				return u[:i+3] + creds[:colon+1] + "***" + "@" + rest[at+1:]
			}
		}
	}
	return u
}
